Lib: Clean up variable that are set but not read
Clean up variables that are set but not read, giving:

keyutils.c: In function 'recursive_key_scan_aux':
keyutils.c:353:46: error: variable 'is_keyring' set but not used [-Werror=unused-but-set-variable]
key.dns_resolver.c: In function 'main':
key.dns_resolver.c:643:7: error: variable 'hostbuf' set but not used [-Werror=unused-but-set-variable]

with the F16 compiler.

Signed-off-by: David Howells <dhowells@redhat.com>